### PR TITLE
Fix error with Share Alliance Post

### PR DESCRIPTION
**Pull request by JRH-1997**
Because of the "$('.customAllianceShareText:first-of-type').click(); " It will reset the Share Alliance Post message to the first message. 
So every time that I forget to select a vehicle and select it, it resets the message. 
I don't see the reason why this should happen with this script.

### CODE REVIEW

**Comment by KBOE2** [comment]
This was introduced to maintain compatibility with a custom version of ShareAlliancePost:
https://forum.leitstellenspiel.de/index.php?thread/13610-sharealliancepost/&postID=294153#post294153

For explanation:
It allowes usage of the Script [Mission-AlarmTime](https://forum.leitstellenspiel.de/index.php?thread/16776-script-mission-alarm-time/) when adjusting the custom Script.

**Comment by JRH-1997** [comment]
Okay, thanks for the explanation.
It looked Strange to me in this script. It's now changing the messages while I'm using the LSSM ShareAlliancePost.

**Comment by JRH-1997** [comment]
Maybe a solutions: Change "customAllianceShareText" to "custom_AllianceShareText" at the LSSM ShareAlliancePost to avoid this reset to the first message.

**Comment by KBOE2** [comment]
That's a great Idea, I will change that tomorrow.

**Comment by KBOE2** [comment]
https://github.com/LSS-Manager/lss-manager-v3/commit/4681e318598794714a8c8f6ab1be224c9091dcc4
I will close here, Update on LSSM will be live probably within this week.

**Pull request closed without merging**
